### ISSUE TITLE
Compiler error while evaluating inline_function.hpp

### ISSUE THREAD

**Issue by StrikeCPP** [Voultapher/Presentations#2]
Hi, I was trying to use inline_function.hpp but faced compilation error while accessing vtable.hpp. The error is as follows:

vtable.hpp:69:33: error: template declaration of 'const detail::vtable<R, Args ...> detail::empty_vtable'
 static const vtable<R, Args...> empty_vtable{};
vtable.hpp:73:19: error: template declaration of 'const auto detail::empty_vtable_ptr'
 static const auto empty_vtable_ptr =
vtable.hpp:74:16: error: 'empty_vtable' was not declared in this scope
 std::addressof(empty_vtable<R, Args...>);
vtable.hpp:74:30: error: expected primary-expression before ',' token
 std::addressof(empty_vtable<R, Args...>);
vtable.hpp:74:36: error: expected primary-expression before '...' token
 std::addressof(empty_vtable<R, Args...>);

g++ -v
gcc version 4.9.4 (Gentoo 4.9.4 p1.2, pie-0.6.4) 
Note: not pasting full output of the command.
dev ~ $ uname -a
Linux dev 4.12.12-gentoo #2 SMP Tue Nov 7 02:26:57 IST 2017 x86_64 Intel(R) Xeon(R) CPU E5-2643 v4 @ 3.40GHz GenuineIntel GNU/Linux
dev ~ $ 

Let me know if there is any other input needed to debug this issue. Like compilation flags etc if required.

**Comment by Voultapher** [comment]
Your issue is with the compiler's C++14 support. [It works starting gcc 5.3](https://godbolt.org/g/39QXgU). However this code is outdated, a much better and maintained version is in the [SG14 repo](https://github.com/WG21-SG14/SG14/blob/master/SG14/inplace_function.h). My suggestion is that you upgrade your compiler. Afaik that can be done without removing your existing toolchain. If you **really** need to compile with this gcc version, I suggest you backport to C++11.
